openapi: 3.0.3

info:
  title: Service-oriented architecture. Lab 1
  description: Route collection manipulating service
  version: 1.0.0

servers:
  - url: 'http://localhost:22400/api/v1'

tags:
  - name: CRUD operations
    description: CRUD operations for route collection
  - name: Additional operations
    description: Additional operations for route collection

paths:
  /routes:
    get:
      tags:
        - CRUD operations
      summary: Get list of all routes with sorting, filtering and pagination
      operationId: getRoutes
      parameters:
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 5
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: sort
          in: query
          description: Sorting arguments array. Use '<' for descending order.
          required: false
          schema:
            type: array
            items:
              type: string
              example: <id
              pattern: '^<{0,1}(id|name|coordinates\.x|coordinates\.y|creationDate|from\.x|from\.y|from\.z|from\.name|to\.x|to\.y|to\.name|distance)$'
          explode: true
        - name: filter
          in: query
          required: false
          description: Filtering arguments array. Use one of '=', '!=', '>', '<', '>=', '<=' between field and arguments
          schema:
            type: array
            items:
              type: string
              example: id=3
              pattern: '^(id|name|coordinates\.x|coordinates\.y|creationDate|from\.x|from\.y|from\.z|from\.name|to\.x|to\.y|to\.name|distance)(=|!=|>|<|>=|<=)(.+)$'
          explode: true
      responses:
        '200':
          description: Routes list
          content:
            application/xml:
              schema:
                type: array
                xml:
                  name: routes
                  wrapped: true
                items:
                  $ref: '#/components/schemas/RouteAllFields'
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'
    post:
      tags:
        - CRUD operations
      summary: Create new route
      operationId: createRoute
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Route'
      responses:
        '200':
          description: Returns the created Route
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RouteAllFields'
        '400':
          description: Invalid input
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorII'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

  /routes/{id}:
    get:
      tags:
        - CRUD operations
      summary: Get route by ID
      operationId: getRoute
      parameters:
        - name: id
          in: path
          description: route id
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 1
            example: 1
      responses:
        '200':
          description: Returns Route
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RouteAllFields'
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

    put:
      tags:
        - CRUD operations
      summary: Modify route by ID
      operationId: modifyRoute
      parameters:
        - name: id
          in: path
          description: route id
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 1
            example: 1
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Route'
      responses:
        '200':
          description: Returns the updated Route
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/RouteAllFields'
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

    delete:
      tags:
        - CRUD operations
      summary: Delete route by ID
      operationId: deleteRoute
      parameters:
        - name: id
          in: path
          description: route id
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 1
            example: 1
      responses:
        '204':
          description: The route was successfully deleted
          content:
            application/xml:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 204
                  message:
                    type: string
                    example: The route was successfully deleted
                  time:
                    type: string
                    format: date-time
                    example: "2024-10-05T00:00:10Z"
                xml:
                  name: NoContent
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

  /routes/size-of-id-groups:
    get:
      tags:
        - Additional operations
      summary: group routes by id and return groups size
      operationId: getIdGroupsSize
      responses:
        '200':
          description: id groups size
          content:
            application/xml:
              schema:
                type: array
                items:
                  type: integer
                  format: int32
                  nullable: false
                  minimum: 1
                example: [ 1,3,2 ]
                xml:
                  name: idGroupsSize
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

  /routes/equals-distance:
    get:
      tags:
        - Additional operations
      summary: Returns routes with distance field equals arg
      operationId: getFlatsCountByTransportGreaterThan
      parameters:
        - name: distance
          in: query
          description: distance for counting
          required: true
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Count of routes with distance field equals param
          content:
            application/xml:
              schema:
                type: integer
                format: int32
                example: 10
                xml:
                  name: count
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returns for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

  /routes/greater-distance:
    get:
      tags:
        - Additional operations
      summary: Returns list of Routes with distance field is greater than param
      operationId: getFlatsByFurnishGreaterThan
      parameters:
        - name: distance
          in: query
          description: distance for filtering
          required: true
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Routes list with distance field is greater than param
          content:
            application/xml:
              schema:
                type: array
                xml:
                  name: routes
                  wrapped: true
                items:
                  $ref: '#/components/schemas/RouteAllFields'
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorDefault'

components:
  schemas:

    Coordinates:
      type: object
      properties:
        x:
          type: number
          format: double
          nullable: false
          maximum: 510
          example: 100.9
        y:
          type: number
          format: double
          nullable: false
          example: 200.5
      xml:
        name: coordinates

    Location:
      type: object
      properties:
        x:
          type: number
          format: float
          nullable: false
          example: 12.34
        y:
          type: number
          format: float
          nullable: false
          example: 23.45
        z:
          type: number
          format: float
          nullable: false
          example: 34.56
        name:
          type: string
          nullable: false
          maxLength: 452
          example: Masha
      xml:
        name: location

    Location2:
      type: object
      properties:
        x:
          type: number
          format: double
          nullable: false
          example: 12.34
        y:
          type: number
          format: float
          nullable: false
          example: 23.45
        name:
          type: string
          nullable: false
          example: Sasha
      xml:
        name: location2

    Route:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
          example: Route №1203
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        from:
          $ref: '#/components/schemas/Location'
        to:
          $ref: '#/components/schemas/Location2'
        distance:
          type: number
          format: float
          nullable: false
          minimum: 1
          exclusiveMinimum: true
      xml:
        name: route

    RouteAllFields:
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              nullable: false
              minimum: 1
              example: 1
              description: unique identifier of flat
            creationDate:
              type: string
              format: date-time
              nullable: false
              example: 2024-10-05T00:00:10Z
        - $ref: '#/components/schemas/Route'

    ErrorDefault:
      type: object
      required:
        - code
        - message
        - time
      properties:
        code:
          type: integer
          format: int32
          example: 404
        message:
          type: string
          example: Not Found
        time:
          type: string
          example: "2024-09-10T00:00:00Z"

    ErrorIQP:
      type: object
      required:
        - code
        - message
        - time
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: Invalid query param
        time:
          type: string
          example: "2024-09-10T00:00:00Z"

    ErrorISE:
      type: object
      required:
        - code
        - message
        - time
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: Internal server error
        time:
          type: string
          example: "2024-09-10T00:00:00Z"

    ErrorII:
      type: object
      required:
        - code
        - message
        - time
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: Invalid input
        time:
          type: string
          example: "2024-09-10T00:00:00Z"