openapi: 3.0.3

info:
  title: Service-oriented architecture. Lab 1
  description: Route collection manipulating service
  version: 1.0.0

servers:
  - url: 'http://localhost:22401/api/v1'

paths:
  /navigator/routes/{id-from}/{id-to}/{order-by}:
    get:
      tags:
        - Navigator operations
      summary: find all routes between the specified locations, sort the list by the specified parameter
      operationId: findAllRoutesBetweenLocations
      parameters:
        - name: id-from
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 1
        - name: id-to
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 2
        - name: order-by
          in: path
          required: true
          schema:
            type: string
            example: <id
            pattern: '^<{0,1}(id|name|coordinates\.x|coordinates\.y|creationDate|from\.x|from\.y|from\.z|from\.name|to\.x|to\.y|to\.name|distance)$'
      responses:
        '200':
          description: List of routes between locations
          content:
            application/xml:
              schema:
                type: array
                xml:
                  name: routes
                  wrapped: true
                items:
                  $ref: './collection-service.yaml#/components/schemas/RouteAllFields'
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: './collection-service.yaml#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: './collection-service.yaml#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: './collection-service.yaml#/components/schemas/ErrorDefault'

  /navigator/route/add/{id-from}/{id-to}/{distance}:
    post:
      tags:
        - Navigator operations
      summary: add new route between locations
      operationId: createNewRouteBetweenLocations
      parameters:
        - name: id-from
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 1
        - name: id-to
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            example: 2
        - name: distance
          in: path
          required: true
          schema:
            type: number
            format: float
            minimum: 0
            example: 1.2

      responses:
        '200':
          description: Список квартир, отсортированный по времени до метро
          content:
            application/xml:
              schema:
                type: array
                xml:
                  name: flats
                  wrapped: true
                items:
                  $ref: './collection-service.yaml#/components/schemas/RouteAllFields'
        '400':
          description: Invalid query param
          content:
            application/xml:
              schema:
                $ref: './collection-service.yaml#/components/schemas/ErrorIQP'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: './collection-service.yaml#/components/schemas/ErrorISE'
        '404':
          description: Returned for other errors
          content:
            application/xml:
              schema:
                $ref: './collection-service.yaml#/components/schemas/ErrorDefault'